import Head from 'next/head'
import {Main} from '../components';
import {Project, projects} from '../data';

// This function gets called at build time
export async function getStaticProps() {
  return {
    props: {
      projects,
    },
  }
}

export default function Index({projects}: {projects: Project[]}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main projects={projects}/>
    </>
  )
}
