import Head from 'next/head'
import {Resume as ResumeMarkup } from '../components';

export default function Resume() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <style>
          {
            `
             :root {
                --page-bg-color: #111;
                --page-text-color: #fff;
                --content-text-color: #fff;
              }
            `
          }
        </style>
      </Head>

      <ResumeMarkup />
    </>
  )
}
