import Head from 'next/head';
import {ProjectPage as ProjectPageMarkup} from '../../components';
import {Project, projects} from '../../data';
import {GetStaticPaths, GetStaticProps} from 'next';

export const getStaticPaths: GetStaticPaths = () => {
  return {
    paths: projects.map(({slug}) => ({params: {slug}})),
    fallback: false,
  }
}

export const getStaticProps: GetStaticProps = ({params}) => {
  return {
    props: {
      project: projects.find(({slug}) => slug === params?.slug) || {}
    },
  }
}

export default function ProjectPage({project}: {project: Project}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <ProjectPageMarkup {...project}/>
    </>
  )
}
